name: indy-node-build
on: [ push, pull_request ]

jobs:
  decorator-checks:
    name: Run decorator checks
    needs: lint
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: m00sey/indy-node-build:latest
    outputs:
      matrix-common: ${{ steps.ctd.outputs.matrix-common }}
      matrix-node: ${{ steps.ctd.outputs.matrix-node }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check test decorators
        id: ctd
        run: |
          chmod +x ./scripts/run_pytest_check.sh
          ./scripts/run_pytest_check.sh

  indy-common:
    name: Build Indy Common
    needs: decorator-checks
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: m00sey/indy-node-build:latest
    strategy:
      matrix: ${{fromJson(needs.decorator-checks.outputs.matrix-common)}}
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[tests]
        continue-on-error: true

      - name: Run Indy Common tests
        run: python3 -m pytest -l -m ${{ matrix.module }} -vv --junitxml=test-result-common-${{ matrix.module }}.xml indy_common

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Indy Common ${{ matrix.module }} Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: test-result-common-${{ matrix.module }}.xml

  indy-node:
    name: Build Indy Node
    needs: decorator-checks
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: m00sey/indy-node-build:latest
    strategy:
      matrix: ${{fromJson(needs.decorator-checks.outputs.matrix-node)}}
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[tests]
        continue-on-error: true

      - name: Run Indy Node ${{ matrix.module }} tests
        run: python3 -m pytest -l -m ${{ matrix.module }} -vv --junitxml=test-result-node-${{ matrix.module }}.xml indy_node

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Indy Node ${{ matrix.module }} Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: test-result-node-${{ matrix.module }}.xml

  lint:
    name: Lint
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: m00sey/indy-node-lint:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: flake8
        run: python3 -m flake8

  publish-rc:
    name: Publish release candidate
    runs-on: ubuntu-20.04
    needs: ['indy-common', 'indy-node']
    if: github.event_name == 'push' && (github.repository == 'm00sey/indy-node' && github.ref == 'refs/heads/release*')
    steps:
      - name: pub
        run: |
          echo "publish"