name: indy-node-build
on: [ push, pull_request ]

jobs:
  workflow-setup:
    runs-on: ubuntu-latest
    outputs:
      CACHE_KEY_LINT: ${{ steps.cache.outputs.CACHE_KEY_LINT }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set outputs
        id: cache
        run: |
          LINT_DOCKERFILE_HASH=${{ hashFiles('.github/workflows/lint/Dockerfile') }}
          echo "::set-output name=CACHE_KEY_LINT::$LINT_DOCKERFILE_HASH"
           
  build-lint-image:
    needs: workflow-setup
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      CACHE_KEY_LINT: ${{ needs.workflow-setup.outputs.CACHE_KEY_LINT }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Try load from cache.
        id: cache-image-lint
        uses: actions/cache@v2
        with:
          path: ${GITHUB.WORKSPACE}/cache
          key: ${{ env.CACHE_KEY_LINT }}
      - name: If NOT found in cache, build and cache image.
        if: steps.cache-image-lint.outputs.cache-hit != 'true'
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io --username ${{ secrets.CR_USER }} --password-stdin
          docker build -f .github/workflows/lint/Dockerfile --no-cache -t ${GITHUB_REPOSITORY}/indy-node-lint:${{ env.CACHE_KEY_LINT }} .
          docker tag ${GITHUB_REPOSITORY}/indy-node-lint:${{ env.CACHE_KEY_LINT }} ghcr.io/${GITHUB_REPOSITORY}/indy-node-lint:latest
          docker push ghcr.io/${GITHUB_REPOSITORY}/indy-node-lint:latest
          mkdir -p ${GITHUB.WORKSPACE}/cache
          touch ${GITHUB.WORKSPACE}/cache/${{ env.CACHE_KEY_LINT }}


  decorator-checks:
    name: Run decorator checks
    needs: lint
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: m00sey/indy-node-build:latest
    outputs:
      matrix-common: ${{ steps.ctd.outputs.matrix-common }}
      matrix-node: ${{ steps.ctd.outputs.matrix-node }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check test decorators
        id: ctd
        run: |
          chmod +x ./scripts/run_pytest_check.sh
          ./scripts/run_pytest_check.sh

  indy_common:
    name: Build Indy Common
    needs: decorator-checks
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: m00sey/indy-node-build:latest
    strategy:
      matrix: ${{fromJson(needs.decorator-checks.outputs.matrix-common)}}
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[tests]
        continue-on-error: true

      - name: Run Indy Common tests
        run: python3 -m pytest -l -m ${{ matrix.module }} -vv --junitxml=test-result-common-${{ matrix.module }}.xml indy_common

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Indy Common ${{ matrix.module }} Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: test-result-common-${{ matrix.module }}.xml

  indy_node:
    name: Build Indy Node
    needs: decorator-checks
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: m00sey/indy-node-build:latest
    strategy:
      matrix: ${{fromJson(needs.decorator-checks.outputs.matrix-node)}}
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[tests]
        continue-on-error: true

      - name: Run Indy Node ${{ matrix.module }} tests
        run: python3 -m pytest -l -m ${{ matrix.module }} -vv --junitxml=test-result-node-${{ matrix.module }}.xml indy_node

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Indy Node ${{ matrix.module }} Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: test-result-node-${{ matrix.module }}.xml

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/m00sey/indy-node/indy-node-lint
    needs:
      - workflow-setup
      - build-lint-image
    steps:      
      - name: Check out code
        uses: actions/checkout@v2

      - name: flake8
        run: python3 -m flake8
          
