name: build
on: [ push, pull_request ]

jobs:
  build-common:
    name: Build Indy Common
    runs-on: ubuntu-18.04
    container: m00sey/indy-node-build:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[tests]

      - name: Run Indy Common tests
        run: python -m pytest -l -vv --junitxml=test-result-common.xml indy_common

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Indy Common Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: test-result-common.xml

  build-indy:
    name: Build Indy Node
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        module: [ anon_creds, api, attrib_txn, auth_rule, claim_def, did, endorser, suspension ]
      fail-fast: false
    container: m00sey/indy-node-build:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.cache/pip
          key: testdeps

      - name: Install dependencies
        run: pip install .[tests]

      - name: Run Indy Node ${{ matrix.module }} tests
        run: python -m pytest -l -m ${{ matrix.module }} -vv --junitxml=test-result-node-${{ matrix.module }}.xml indy_node

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Indy Node ${{ matrix.module }} Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: test-result-node-${{ matrix.module }}.xml

  lint:
    name: Lint
    runs-on: ubuntu-18.04
    container: m00sey/indy-node-lint:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: flake8
        run: python3 -m flake8
